In [2]:
pip install -n dis ipykernel --update-deps --force-reinstall;



Usage:   
  /usr/local/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/local/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/local/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /usr/local/bin/python3 -m pip install [options] [-e] <local project path> ...
  /usr/local/bin/python3 -m pip install [options] <archive url/path> ...

no such option: -n
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 1.1 MB/s eta 0:00:0000:0100:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 KB 3.5 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 KB 3.9 MB/s eta 0:00:00a 0:00:01
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd

In [8]:
customer_master=pd.read_csv('customer_master.csv')
customer_master.head()

customer_id customer_name    registration_date customer_name_kana   
0    IK152942        平田 裕次郎  2019-01-01 00:25:33          ひらた ゆうじろう  \
1    TS808488         田村 詩織  2019-01-01 01:13:45            たむら しおり   
2    AS834628         久野 由樹  2019-01-01 02:00:14             ひさの ゆき   
3    AS345469          鶴岡 薫  2019-01-01 04:48:22           つるおか かおる   
4    GD892565         大内 高史  2019-01-01 04:54:51           おおうち たかし   

                         email gender  age      birth pref  
0  hirata_yuujirou@example.com      M   29  1990/6/10  石川県  
1    tamura_shiori@example.com      F   33  1986/5/20  東京都  
2      hisano_yuki@example.com      F   63   1956/1/2  茨城県  
3   tsuruoka_kaoru@example.com      M   74  1945/3/25  東京都  
4   oouchi_takashi@example.com      M   54   1965/8/5  千葉県

In [21]:
item_master=pd.read_csv('item_master.csv')
item_master.head()

item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000

In [22]:
transaction_1=pd.read_csv('transaction_1.csv')
transaction_1.head()

transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502
1    T0000000114   50000  2019-02-01 01:37:23    HD678019
2    T0000000115  120000  2019-02-01 02:34:19    HD298120
3    T0000000116  210000  2019-02-01 02:47:23    IK452215
4    T0000000117  170000  2019-02-01 04:33:46    PL542865

In [23]:
transaction_detail_1=pd.read_csv('transaction_detail_1.csv')
transaction_detail_1.head()

detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1
1          1    T0000000114    S001         1
2          2    T0000000115    S003         1
3          3    T0000000116    S005         1
4          4    T0000000117    S002         2

In [24]:
transaction_2=pd.read_csv('transaction_2.csv')
transaction = pd.concat([transaction_1,transaction_2], ignore_index=True)
transaction.head()

transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502
1    T0000000114   50000  2019-02-01 01:37:23    HD678019
2    T0000000115  120000  2019-02-01 02:34:19    HD298120
3    T0000000116  210000  2019-02-01 02:47:23    IK452215
4    T0000000117  170000  2019-02-01 04:33:46    PL542865

In [13]:
print(len(transaction_1))
print(len(transaction_2))
print(len(transaction))


5000
1786
6786


In [26]:
transaction_detail_2=pd.read_csv('transaction_detail_2.csv')
transaction_detail = pd.concat([transaction_detail_1,transaction_detail_2], ignore_index=True)
transaction_detail.head()

detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1
1          1    T0000000114    S001         1
2          2    T0000000115    S003         1
3          3    T0000000116    S005         1
4          4    T0000000117    S002         2

In [27]:
join_data= pd.merge(transaction_detail, transaction[["transaction_id", "payment_date", "customer_id"]], on="transaction_id", how="left")
join_data.head()

detail_id transaction_id item_id  quantity         payment_date customer_id
0          0    T0000000113    S005         1  2019-02-01 01:36:57    PL563502
1          1    T0000000114    S001         1  2019-02-01 01:37:23    HD678019
2          2    T0000000115    S003         1  2019-02-01 02:34:19    HD298120
3          3    T0000000116    S005         1  2019-02-01 02:47:23    IK452215
4          4    T0000000117    S002         2  2019-02-01 04:33:46    PL542865

In [28]:
join_data= pd.merge(join_data, customer_master, on="customer_id", how="left")
join_data= pd.merge(join_data, item_master, on="item_id", how="left")
join_data.head()

detail_id transaction_id item_id  quantity         payment_date   
0          0    T0000000113    S005         1  2019-02-01 01:36:57  \
1          1    T0000000114    S001         1  2019-02-01 01:37:23   
2          2    T0000000115    S003         1  2019-02-01 02:34:19   
3          3    T0000000116    S005         1  2019-02-01 02:47:23   
4          4    T0000000117    S002         2  2019-02-01 04:33:46   

  customer_id customer_name    registration_date customer_name_kana   
0    PL563502         井本 芳正  2019-01-07 14:34:35           いもと よしまさ  \
1    HD678019         三船 六郎  2019-01-27 18:00:11           みふね ろくろう   
2    HD298120         山根 小雁  2019-01-11 08:16:02            やまね こがん   
3    IK452215         池田 菜摘  2019-01-10 05:07:38            いけだ なつみ   
4    PL542865         栗田 憲一  2019-01-25 06:46:05           くりた けんいち   

                         email gender  age       birth pref item_name   
0  imoto_yoshimasa@example.com      M   30   1989/7/15  熊本県      PC-E  \
1   mifune_rokurou@example.com      M   73  1945/11/29  京都府      PC-A   
2     yamane_kogan@example.com      M   42   1977/5/17  茨城県      PC-C   
3    ikeda_natsumi@example.com      F   47   1972/3/17  兵庫県      PC-E   
4   kurita_kenichi@example.com      M   74  1944/12/17  長崎県      PC-B   

   item_price  
0      210000  
1       50000  
2      120000  
3      210000  
4       85000

In [29]:
join_data["price"]= join_data["quantity"]*join_data["item_price"]
join_data[["quantity","item_price","price"]].head()

quantity  item_price   price
0         1      210000  210000
1         1       50000   50000
2         1      120000  120000
3         1      210000  210000
4         2       85000  170000

In [30]:
print(join_data["price"].sum())
print(transaction["price"].sum())

971135000
971135000


In [31]:
join_data["price"].sum() == transaction["price"].sum()

True

In [32]:
join_data.isnull().sum()

detail_id             0
transaction_id        0
item_id               0
quantity              0
payment_date          0
customer_id           0
customer_name         0
registration_date     0
customer_name_kana    0
email                 0
gender                0
age                   0
birth                 0
pref                  0
item_name             0
item_price            0
price                 0
dtype: int64

In [33]:
join_data.describe()

detail_id     quantity          age     item_price          price
count  7144.000000  7144.000000  7144.000000    7144.000000    7144.000000
mean   3571.500000     1.199888    50.265677  121698.628219  135937.150056
std    2062.439494     0.513647    17.190314   64571.311830   68511.453297
min       0.000000     1.000000    20.000000   50000.000000   50000.000000
25%    1785.750000     1.000000    36.000000   50000.000000   85000.000000
50%    3571.500000     1.000000    50.000000  102500.000000  120000.000000
75%    5357.250000     1.000000    65.000000  187500.000000  210000.000000
max    7143.000000     4.000000    80.000000  210000.000000  420000.000000

In [34]:
print(join_data["payment_date"].min())
print(join_data["payment_date"].max())

2019-02-01 01:36:57
2019-07-31 23:41:38


In [35]:
join_data.dtypes

detail_id              int64
transaction_id        object
item_id               object
quantity               int64
payment_date          object
customer_id           object
customer_name         object
registration_date     object
customer_name_kana    object
email                 object
gender                object
age                    int64
birth                 object
pref                  object
item_name             object
item_price             int64
price                  int64
dtype: object

In [57]:
join_data["payment_date"] = pd.to_datetime(join_data["payment_date"])
join_data["payment_month"] = join_data["payment_date"].dt.strftime("%Y%m")
join_data[["payment_date", "payment_month"]].head()

payment_date payment_month
0 2019-02-01 01:36:57        201902
1 2019-02-01 01:37:23        201902
2 2019-02-01 02:34:19        201902
3 2019-02-01 02:47:23        201902
4 2019-02-01 04:33:46        201902

In [58]:
join_data.groupby("payment_month").sum()["price"]

TypeError: datetime64 type does not support sum operations

In [50]:
join_data.groupby(["payment_month", "item_name"]).sum()[["price","quantity"]]

TypeError: datetime64 type does not support sum operations

In [13]:
import numpy as np
a = np.array([[1, 2, 3],
              [3, 4,7]])

b = np.repeat(a, 2, axis=0)
print(b)

[[1 2 3]
 [1 2 3]
 [3 4 7]
 [3 4 7]]


In [2]:
import random

# 1から49までの範囲からランダムに3つの数値を選ぶ
random_numbers = random.sample(range(1, 50), 3)

print(random_numbers)

[23, 47, 34]
